server:
  # 服务端口号
  port: 8100
spring:
  application:
    # 配置服务名称
    name: test-app
  datasource:
    # MYSQL数据库驱动
    driver-class-name: com.mysql.cj.jdbc.Driver
    # 数据库地址
    url: jdbc:mysql://localhost:3306/test_local?useUnicode=true&characterEncoding=utf8&useSSL=false&autoReconnect=true&createDatabaseIfNotExist=true&serverTimezone=UTC
    # 数据库用户名
    username: root
    # 数据库密码
    password: 123456
  jpa:
    # 配置数据库类型
    database: MYSQL
    # 开发时显示sql，部署到生产环境时设为false
    show-sql: true
    # Hibernate相关配置
    hibernate:
      # 配置级联等级
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
#        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

# LOGGING
logging:
  level:
    root: info